/*
 * To change this license header, choose License Headers in Project Properties.
 * Owen Figueroa -10-
 */
package Visual;

import javax.swing.JOptionPane;

/**
 *
 * @author Owen Figueroa
 */
public class MenuInicial extends javax.swing.JPanel {

    /**
     * Creates new form MenuInicial
     */
    public MenuInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        logIn = new javax.swing.JButton();
        createUser = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setPreferredSize(new java.awt.Dimension(624, 485));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Hobo Std", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("USERNAME");
        add(jLabel1);
        jLabel1.setBounds(440, 200, 190, 50);

        jLabel2.setFont(new java.awt.Font("Hobo Std", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PASSWORD");
        jLabel2.setPreferredSize(new java.awt.Dimension(54, 14));
        add(jLabel2);
        jLabel2.setBounds(450, 320, 170, 40);

        user.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        add(user);
        user.setBounds(390, 260, 290, 40);

        logIn.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        logIn.setText("Log In");
        logIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logInMouseClicked(evt);
            }
        });
        logIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInActionPerformed(evt);
            }
        });
        add(logIn);
        logIn.setBounds(370, 480, 130, 40);

        createUser.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        createUser.setText("Create User");
        createUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createUserMouseClicked(evt);
            }
        });
        add(createUser);
        createUser.setBounds(580, 480, 140, 40);

        Exit.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        Exit.setText("Salir");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        add(Exit);
        Exit.setBounds(920, 570, 120, 40);

        pass.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        add(pass);
        pass.setBounds(390, 370, 290, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/titulo.png"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(290, 60, 500, 120);

        jLabel4.setFont(new java.awt.Font("Hobo Std", 0, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(0, 0, 1150, 650);
    }// </editor-fold>//GEN-END:initComponents

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void logInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logInMouseClicked
        // TODO add your handling code here:
        if(Menu.users.login(user.getText(), pass.getText())){
            Menu.menu.setPanel(new MenuPrincipal());
            Menu.userLogged=user.getText();
        }
        else{
            JOptionPane.showConfirmDialog(Menu.menu, "Usuario o contraseña invalida", "Informacion",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_logInMouseClicked

    private void createUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createUserMouseClicked
        // TODO add your handling code here:
        if(Menu.users.saveUser(user.getText(), pass.getText())){
            Menu.menu.setPanel(new MenuPrincipal());
            Menu.userLogged=user.getText();
        }
        else{
            JOptionPane.showConfirmDialog(Menu.menu, "Usuario ya existente o contraseña invalida", "Informacion",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_createUserMouseClicked

    private void logInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logInActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton createUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton logIn;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
