/*
 * To change this license header, choose License Headers in Project Properties.
 * Owen Figueroa -10-
 */
package Visual;

import static Visual.Menu.menu;
import java.util.Calendar;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author Owen Figueroa
 */
public class MiCuenta extends javax.swing.JPanel {

    /**
     * Creates new form MiCuenta
     */
    public MiCuenta() {
        try{
        initComponents();
        String[] info = Menu.users.search(Menu.userLogged).split("-");
        jLabel1.setText(info[0]);
        jLabel2.setText(info[1]);
        Calendar cal = Calendar.getInstance();
        cal.setTimeInMillis(Long.parseLong(info[2]));
        int dia = cal.get(Calendar.DAY_OF_MONTH);
        String mes = cal.getDisplayName(Calendar.MONTH, Calendar.LONG, Locale.forLanguageTag("es"));
        int año=cal.get(Calendar.YEAR);
        jLabel3.setText(dia+"/"+mes+"/"+año);
        }catch(Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnFacebook = new javax.swing.JButton();
        btnCambiarPassword = new javax.swing.JButton();
        btnTwitter = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Hobo Std", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nombre");
        add(jLabel1);
        jLabel1.setBounds(480, 70, 240, 30);

        btnFacebook.setFont(new java.awt.Font("Hobo Std", 0, 24)); // NOI18N
        btnFacebook.setText("Conectar a Facebook");
        btnFacebook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFacebookMouseClicked(evt);
            }
        });
        btnFacebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacebookActionPerformed(evt);
            }
        });
        add(btnFacebook);
        btnFacebook.setBounds(660, 290, 270, 60);

        btnCambiarPassword.setFont(new java.awt.Font("Hobo Std", 0, 24)); // NOI18N
        btnCambiarPassword.setText("Cambiar Password");
        btnCambiarPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCambiarPasswordMouseClicked(evt);
            }
        });
        add(btnCambiarPassword);
        btnCambiarPassword.setBounds(300, 290, 270, 60);

        btnTwitter.setFont(new java.awt.Font("Hobo Std", 0, 24)); // NOI18N
        btnTwitter.setText("Conectar a Twitter");
        btnTwitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTwitterMouseClicked(evt);
            }
        });
        add(btnTwitter);
        btnTwitter.setBounds(300, 400, 270, 60);

        btnEliminar.setFont(new java.awt.Font("Hobo Std", 0, 24)); // NOI18N
        btnEliminar.setText("Eliminar Cuenta");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        add(btnEliminar);
        btnEliminar.setBounds(660, 400, 270, 60);

        btnRegresar.setFont(new java.awt.Font("Hobo Std", 0, 24)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });
        add(btnRegresar);
        btnRegresar.setBounds(890, 560, 220, 50);

        jLabel2.setFont(new java.awt.Font("Hobo Std", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Puntaje");
        add(jLabel2);
        jLabel2.setBounds(480, 140, 240, 30);

        jLabel3.setFont(new java.awt.Font("Hobo Std", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Fecha");
        add(jLabel3);
        jLabel3.setBounds(480, 200, 240, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(0, 0, 1150, 650);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        // TODO add your handling code here:
        Menu.menu.setPanel(new MenuPrincipal());
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnCambiarPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCambiarPasswordMouseClicked
        // TODO add your handling code here:
        try{
        Menu.users.changePassword();
        }catch(Exception e){}
    }//GEN-LAST:event_btnCambiarPasswordMouseClicked

    private void btnFacebookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacebookMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(menu, "PROXIMAMENTE ESTARA DISPONIBLE", "Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnFacebookMouseClicked

    private void btnTwitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTwitterMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(menu, "PROXIMAMENTE ESTARA DISPONIBLE", "Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnTwitterMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        // TODO add your handling code here:
        try{
        Menu.users.deleteUser(Menu.userLogged);
        }catch(Exception e){}
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnFacebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacebookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFacebookActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarPassword;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFacebook;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnTwitter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
